### ISSUE TITLE
Comparison to tokio

### ISSUE THREAD

**Issue by manuels** [dwango/fibers-rs#10]
Interesting crate. How does it compare to tokio? Are futures compatible? Can I use both tokio and fibers in my project? And can I use crates that depend on tokio with fibers?

**Comment by sile** [comment]
Thank you for being interested in this crate.

> How does it compare to tokio? 

This crate started developing before a stable version of `tokio` is released. And I hardly have used `tokio`. So, honestly, I cannot give you an appropriate comparison.

> Are futures compatible?

Basically, yes. This is a library for executing instances that implement `futures:Future` trait. But, this crate uses own channels (e.g., `fibers::sync::{mpsc, oneshot}`) instead of the ones provided by `futures` create. Besides, `fibers` does not use `futures::{executor, task}` modules.

> Can I use both tokio and fibers in my project? And can I use crates that depend on tokio with fibers?

Although it is theoretically possible, it may be cumbersome. As stated above, `fibers` has its own channels (and TCP/UDP sockets). So, for example, if you want to exchange messages between a `tokio` future and a `fibers` future, you need to select the appropriate channel according to the recipient.

**Comment by manuels** [comment]
Great, thanks for your response, @sile!
