### ISSUE TITLE
Add new tasks after the creation of an executor

### ISSUE THREAD

**Issue by astonbitecode** [dwango/fibers-rs#13]
Hi,

Is it somehow possible for an `Executor` to be shared between threads and also be used for adding new tasks during runtime?

I am thinking of something like:

```rust
// Create a shared executor
let mut executor_mutex = Arc::new(Mutex::new(ThreadPoolExecutor::new().unwrap()));

// Clone it
let ce = executor_mutex.clone();

// A different thread, at some poipnt spawns new tasks on the executor
thread::spawn(move || {
    let mut executor = ce.lock().unwrap();
    executor.spawn(futures::lazy(|| { println!("Hello"); Ok(())} ));
});

let executor = executor_mutex.lock().unwrap();

// Run the executor
// Not possible, since the run method consumes the executor
executor.run();
```

I see that there is the `run_once`, but I suppose that this blocks until all the units that it includes finish. This would make the executor practically unavailable until then I guess.

On the other hand, I could just create one new executor whenever I wanted to execute some tasks, but then the occupied threads on the system would increase drastically if there are a lot of tasks to be executed and these tasks are long-lived...

**Comment by sile** [comment]
Thank you for your question. There are two ways for handling such situation.

(1) Send handles instead of executors
------------------------------------------

[`Executor`](https://docs.rs/fibers/0.1/fibers/trait.Executor.html) trait provides `handle` method. By calling this method, you can create any number of handles that can be sent to separate threads. Since handles implement [`Spawn`](https://docs.rs/fibers/0.1/fibers/trait.Spawn.html) trait, you can spawn futures via a handle without executors.
Running examples that use handles are found in [fibers-rs/examples/](https://github.com/dwango/fibers-rs/blob/master/examples/) directory.

(2) Use [`fibers_global`](https://docs.rs/fibers_global/) crate
-----------------------------------------------------------------

This crate manages the global `ThreadPoolExecutor` instead of you, and provides `fibers_global::spawn` method that can be called anywhere within your code.
`fibers_global` is convenient if you don't need advanced features such as managing multiple executors in a single program.

**Comment by astonbitecode** [comment]
Thank you for the suggestions. I didn't know about the `fibers_global` crate. 

I will give it a try, I don't have more complex cases for now.
