### ISSUE TITLE
Time to make a new release?

### ISSUE THREAD

**Issue by ckaran** [dwango/fibers-rs#25]
I saw that you updated to the 2018 edition of rust recently, but the published version on crates.io is from earlier; maybe it's time to publish a new version?

**Comment by koba-e964** [comment]
Thank you for creating an issue!
Well, actually, we don't think updating to Rust 2018 deserves a new release. From the users' perspective there are no changes: whether this crate uses Rust 2015 or Rust 2018 is irrelevant to the users of this crate because it's okay to have Rust 2018 crates depending on Rust 2015 crates, and vice-versa.
We will release a new version once some functionality is added or changed. Closing.
